server:
  port: 9002
spring:
  application:
    name: ORDERS-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://diagnostic51.tk/eureka/
  instance:
    hostname: diagnostic51.tk
