server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: USERS-SERVICE
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**
        - id: PATIENTS-SERVICE
          uri: lb://PATIENTS-SERVICE
          predicates:
            - Path=/patients/**
        - id: ORDERS-SERVICE
          uri: lb://ORDERS-SERVICE
          predicates:
            - Path=/orders/**
        - id: ADDRESSES-SERVICE
          uri: lb://ADDRESSES-SERVICE
          predicates:
            - Path=/address/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://diagnostic51.tk/eureka/
      instance:
        hostname: diagnostic51.tk