server:
  port: 9004
spring:
  application:
    name: USERS-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://diagnostic51.tk/eureka/
  instance:
    hostname: diagnostic51.tk